# Generated by Django 5.1.1 on 2024-11-30 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrators', '0001_initial'),
        ('members', '0001_initial'),
        ('mutualApp', '0002_session_create_at_alter_exercise_create_at'),
        ('operationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('administrator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrators.administrator')),
                ('borrowing_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operationApp.borrowing')),
                ('member_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutualApp.session')),
            ],
        ),
    ]
