# Generated by Django 5.1.1 on 2024-11-14 16:48

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=30)),
                ('type', models.CharField(default='member', max_length=30)),
                ('sex', models.CharField(blank=True, max_length=8)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('avatar', models.ImageField(default='posts/default.jpg', upload_to=users.models.upload_to, verbose_name='Image')),
                ('tel', models.CharField(max_length=9)),
                ('address', models.CharField(max_length=50)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
