# Generated by Django 5.1.1 on 2025-01-28 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrators', '0001_initial'),
        ('members', '0001_initial'),
        ('mutualApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epargne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('administrator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrators.administrator')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epargne_from_savings', to='members.member')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutualApp.session')),
            ],
        ),
    ]
