# Generated by Django 5.1.1 on 2025-01-28 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrators', '0001_initial'),
        ('members', '0001_initial'),
        ('mutualApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('administrator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_from_operationApp', to='administrators.administrator')),
                ('exercise_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mutualApp.exercise')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutualApp.session')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('administrator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrators.administrator')),
                ('exercise_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mutualApp.exercise')),
                ('member_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_from_operationApp', to='members.member')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutualApp.session')),
            ],
        ),
        migrations.CreateModel(
            name='HelpType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default="type d'aide", max_length=255, null=True)),
                ('amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operationApp.operation')),
                ('amount_borrowed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date_line', models.DateTimeField()),
                ('state', models.BooleanField(default=False)),
                ('late', models.BooleanField(default=False)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('interest_distribution', models.JSONField(default=dict)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings_from_operationApp', to='members.member')),
            ],
            bases=('operationApp.operation',),
        ),
        migrations.CreateModel(
            name='Epargne',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operationApp.operation')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epargnes_from_operationApp', to='members.member')),
            ],
            bases=('operationApp.operation',),
        ),
        migrations.CreateModel(
            name='ObligatoryContribution',
            fields=[
                ('contribution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operationApp.contribution')),
                ('contributed', models.BooleanField(default=False)),
                ('amount', models.FloatField(default=10000)),
            ],
            bases=('operationApp.contribution',),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('administrator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrators.administrator')),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutualApp.exercise')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds_from_operationApp', to='members.member')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutualApp.session')),
                ('borrowing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operationApp.borrowing')),
            ],
        ),
        migrations.CreateModel(
            name='RefundDistributionTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('real_time_amount_before', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('real_time_amount_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operationApp.refund')),
                ('epargne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operationApp.epargne')),
            ],
        ),
        migrations.CreateModel(
            name='LoanUtilizationTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_used', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('real_time_amount_before', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('real_time_amount_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operationApp.borrowing')),
                ('epargne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operationApp.epargne')),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operationApp.operation')),
                ('limit_date', models.DateField()),
                ('amount_expected', models.FloatField(blank=True, null=True)),
                ('comments', models.TextField(max_length=255)),
                ('state', models.BooleanField(default=True)),
                ('collected_amount', models.FloatField(default=0)),
                ('help_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operationApp.helptype')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_help_set', to='members.member')),
            ],
            bases=('operationApp.operation',),
        ),
        migrations.CreateModel(
            name='PersonalContribution',
            fields=[
                ('contribution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operationApp.contribution')),
                ('date', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(default=0)),
                ('help_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operationApp.help')),
            ],
            bases=('operationApp.contribution',),
        ),
    ]
