# Generated by Django 5.1.1 on 2024-11-30 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrators', '0001_initial'),
        ('members', '0001_initial'),
        ('mutualApp', '0002_session_create_at_alter_exercise_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('administrator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrators.administrator')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutualApp.session')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('administrator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrators.administrator')),
                ('member_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutualApp.session')),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operationApp.operation')),
                ('interest', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_borrowed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_to_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_date_line', models.DateTimeField(blank=True, null=True)),
                ('state', models.BooleanField(default=False)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings_from_operation', to='members.member')),
            ],
            bases=('operationApp.operation',),
        ),
        migrations.CreateModel(
            name='ObligatoryContribution',
            fields=[
                ('contribution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operationApp.contribution')),
                ('contributed', models.BooleanField(default=False)),
                ('amount', models.IntegerField(default=10000)),
            ],
            bases=('operationApp.contribution',),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('administrator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds_from_operation', to='administrators.administrator')),
                ('member_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='refunds_from_operation', to='members.member')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds_from_operation', to='mutualApp.session')),
                ('borrowing_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds_from_operation', to='operationApp.borrowing')),
            ],
        ),
        migrations.CreateModel(
            name='Epargne',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operationApp.operation')),
                ('amount', models.IntegerField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epargne_from_operation', to='members.member')),
            ],
            bases=('operationApp.operation',),
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operationApp.operation')),
                ('limit_date', models.DateField()),
                ('amount_expected', models.IntegerField()),
                ('comments', models.TextField(max_length=255)),
                ('state', models.BooleanField(default=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_help_set', to='members.member')),
            ],
            bases=('operationApp.operation',),
        ),
        migrations.CreateModel(
            name='PersonalContribution',
            fields=[
                ('contribution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operationApp.contribution')),
                ('date', models.CharField(max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('help_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operationApp.help')),
            ],
            bases=('operationApp.contribution',),
        ),
    ]
