# Generated by Django 5.1.1 on 2024-11-14 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0001_initial'),
        ('members', '0001_initial'),
        ('mutualApp', '0001_initial'),
        ('operationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operationApp.operation')),
                ('interest', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_borrowed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_to_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_date_line', models.DateTimeField(blank=True, null=True)),
                ('state', models.BooleanField(default=False)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings_from_operation', to='members.member')),
            ],
            bases=('operationApp.operation',),
        ),
        migrations.CreateModel(
            name='Epargne',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operationApp.operation')),
                ('amount', models.IntegerField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epargne_from_operation', to='members.member')),
            ],
            bases=('operationApp.operation',),
        ),
        migrations.CreateModel(
            name='ObligatoryContribution',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operationApp.operation')),
                ('contributed', models.BooleanField(default=False)),
                ('amount', models.IntegerField(default=10000)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            bases=('operationApp.operation',),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('administrator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds_from_operation', to='administrators.administrator')),
                ('borrowing_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds_from_operation', to='operationApp.borrowing')),
                ('member_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='refunds_from_operation', to='members.member')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds_from_operation', to='mutualApp.session')),
            ],
        ),
    ]
