# Generated by Django 5.1.1 on 2024-12-17 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0001_initial'),
        ('members', '0002_remove_member_administrator_id_and_more'),
        ('mutualApp', '0003_tresorerie_total_borrowings_tresorerie_total_savings_and_more'),
        ('operationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='loan_distribution',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='epargne',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='epargne',
            name='real_time_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='refund',
            name='redistribution_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='id',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='epargne',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='help',
            name='amount_expected',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='obligatorycontribution',
            name='amount',
            field=models.FloatField(default=10000),
        ),
        migrations.AlterField(
            model_name='refund',
            name='administrator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_operation_app', to='administrators.administrator'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='refund',
            name='borrowing_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds_operation_app', to='operationApp.borrowing'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds_operation_app', to='members.member'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds_operation_app', to='mutualApp.session'),
        ),
        migrations.CreateModel(
            name='LoanUtilizationTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_used', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('real_time_amount_before', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('real_time_amount_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operationApp.borrowing')),
                ('epargne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operationApp.epargne')),
            ],
        ),
        migrations.CreateModel(
            name='RefundDistributionTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('real_time_amount_before', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('real_time_amount_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('epargne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operationApp.epargne')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operationApp.refund')),
            ],
        ),
    ]
