# Generated by Django 5.1.1 on 2024-12-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationApp', '0002_borrowing_loan_distribution_epargne_base_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='payment_date_line',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
