# Generated by Django 5.1.3 on 2025-03-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationApp', '0002_remove_help_limit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligatorycontribution',
            name='contributed',
            field=models.BooleanField(default=True),
        ),
    ]
