# Generated by Django 5.1.3 on 2025-05-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationApp', '0003_alter_obligatorycontribution_contributed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligatorycontribution',
            name='contributed',
            field=models.BooleanField(default=False),
        ),
    ]
