# Generated by Django 5.1.1 on 2024-12-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationApp', '0003_alter_borrowing_payment_date_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='is_redistributed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personalcontribution',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
