# Generated by Django 5.1.1 on 2024-12-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationApp', '0004_refund_is_redistributed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='payment_date_line',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
