# Generated by Django 5.1.1 on 2025-01-28 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('administrator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrators.administrator')),
            ],
        ),
        migrations.CreateModel(
            name='FondSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutualApp.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('SAVING', 'Épargne'), ('BORROWING', 'Emprunt'), ('CLOSED', 'Fermée')], default='SAVING', max_length=20)),
                ('administrator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrators.administrator')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutualApp.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Tresorerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutualApp.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tresorerie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutualApp.tresorerie')),
            ],
        ),
    ]
