# Generated by Django 5.1.1 on 2024-11-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutualApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='create_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='create_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
