# Generated by Django 5.1.1 on 2024-12-17 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutualApp', '0002_session_create_at_alter_exercise_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tresorerie',
            name='total_borrowings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tresorerie',
            name='total_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tresorerie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutualApp.tresorerie')),
            ],
        ),
    ]
