# Generated by Django 5.1.1 on 2024-11-14 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowing_savings', '0001_initial'),
        ('borrowings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing_saving',
            name='borrowing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowings.borrowing'),
        ),
    ]
