# Generated by Django 5.1.1 on 2024-11-30 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowing_savings', '0001_initial'),
        ('operationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing_saving',
            name='borrowing_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operationApp.borrowing'),
        ),
        migrations.AddField(
            model_name='borrowing_saving',
            name='epargne_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operationApp.epargne'),
        ),
    ]
