# Generated by Django 5.1.1 on 2024-11-14 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing_savings', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing_saving',
            name='saving_id',
        ),
    ]
