# Generated by Django 5.1.1 on 2025-01-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='has_contribued_for_session',
            field=models.BooleanField(default=False),
        ),
    ]
