# Generated by Django 5.1.1 on 2024-12-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='administrator_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='inscription',
        ),
        migrations.RemoveField(
            model_name='member',
            name='social_crown',
        ),
        migrations.AddField(
            model_name='member',
            name='total_borrowings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='member',
            name='total_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
