# Generated by Django 5.1.3 on 2024-12-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_member_administrator_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='inscription',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
    ]
