# Generated by Django 5.1.1 on 2024-12-21 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0001_initial'),
        ('members', '0003_member_insciption'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='administrator_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrators.administrator'),
            preserve_default=False,
        ),
    ]
