# Generated by Django 5.1.1 on 2024-12-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_administrator_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='insciption',
            new_name='inscription',
        ),
    ]
